<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CategoryForm.aspx.cs" Inherits="TSQLWEB.CategoryForm" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Stylesheets" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <br/>
	<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Category Form</h3>
        </div>
        <div class="panel-body">
          <table cellpadding="5px">
	<tr >
	<td style="width: 20%; text-align:right" > Category Name:</td>
	<td style="width: 70%"><asp:TextBox ID="txtCategory" cssClass="form-control" runat="server" Width="206px" MaxLength="15"/>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtCategory" ErrorMessage="Invalid Category Name!" ForeColor="Red"></asp:RequiredFieldValidator>
        </td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Description:</td>
	<td style="width: 70%"><asp:TextBox ID="txtDes" cssClass="form-control" runat="server" Width="206px" Height="180px" MaxLength="200"/>
        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="txtDes" ErrorMessage="Invalid Description!" ForeColor="Red"></asp:RequiredFieldValidator>
        </td>
	</tr>
</table>

        </div>
      </div>
	


    <br />
    <div style="margin: auto">
	 <asp:Button ID="btnNew"  cssClass="btn btn-default" runat="server" Text="New" OnClick="btnNew_Click" />
  <asp:Button ID="btnAdd" cssClass="btn btn-success" runat="server" Text="Add" OnClick="btnAdd_Click" />
	</div>	
    <br />
    <script>
   </script>
        <asp:Label ID="lblStatus" runat="server"></asp:Label>
        <%--<div id="alert" class="alert alert-success fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">Close &times;</a>
    <strong>Success!</strong> Add completely! 
    </div>--%>
    <asp:GridView ID="GridView1" CssClass="col-md-3" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnRowDeleting="GridView1_RowDeleting1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="100%" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical">
        <AlternatingRowStyle BackColor="White"></AlternatingRowStyle>

        <FooterStyle BackColor="#CCCC99"></FooterStyle>

        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White"></HeaderStyle>

        <PagerStyle HorizontalAlign="Right" BackColor="#F7F7DE" ForeColor="Black"></PagerStyle>

        <RowStyle BackColor="#F7F7DE"></RowStyle>

        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White"></SelectedRowStyle>

        <SortedAscendingCellStyle BackColor="#FBFBF2"></SortedAscendingCellStyle>

        <SortedAscendingHeaderStyle BackColor="#848384"></SortedAscendingHeaderStyle>

        <SortedDescendingCellStyle BackColor="#EAEAD3"></SortedDescendingCellStyle>

        <SortedDescendingHeaderStyle BackColor="#575357"></SortedDescendingHeaderStyle>
    </asp:GridView>

    <br />
 
</asp:Content>
