<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProductForm.aspx.cs" Inherits="TSQLWEB.ProductForm" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Supplier Form</h3>
        </div>
        <div class="panel-body">
            <table cellspacing="15px" >
                <tr>
                    <td style="text-align: right" class="auto-style3">Product id:</td>
                    <td class="auto-style4">
                        <asp:TextBox ID="txtProductId" CssClass="form-control" runat="server" Width="206px" Enabled="False" /></td>
                </tr>
                <tr>
                    <td style="width: 20%; text-align: right">Product Name:</td>
                    <td style="width: 70%">
                        <asp:TextBox ID="txtProductName" CssClass="form-control" runat="server" Width="206px" />
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Product name is not null" ControlToValidate="txtProductName" ForeColor="Red"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td style="width: 20%; text-align: right">Supplier id:</td>
                    <td style="width: 70%">
                        <asp:TextBox ID="txtSupp" CssClass="form-control" runat="server" Width="206px"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="Supplier id is number !!!" ControlToValidate="txtSupp" ForeColor="Red"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td style="width: 20%; text-align: right">Category id:</td>
                    <td style="width: 70%">
                        <asp:TextBox ID="txtCate" CssClass="form-control" runat="server" Width="206px"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="Category id is number !!! " ControlToValidate="txtCate" ForeColor="Red"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right" class="auto-style1">Unitprice:</td>
                    <td class="auto-style2">
                        <asp:TextBox ID="txtUnitprice" CssClass="form-control" runat="server" Width="206px"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ErrorMessage="Unitprice is number !!!" ControlToValidate="txtUnitprice" ForeColor="Red"></asp:RequiredFieldValidator>
                    </td>
                </tr>

                <tr>
                    <td style="width: 20%; text-align: right">Discontinued</td>
                    <td style="width: 70%">
                        <asp:CheckBox ID="cbDis" runat="server" />
                </tr>
            </table>

        </div>
    </div>

    <br />
    <div class="btn btn-default">
        <asp:Button ID="btnNew" runat="server" Text="New" OnClick="btnNew_Click"  />

    </div>
    <div class="btn btn-success">
        <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click" />
    </div>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnRowEditing="GridView1_RowEditing" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDeleting="GridView1_RowDeleting"></asp:GridView>
</asp:Content>

<asp:Content ID="Content2" runat="server" contentplaceholderid="Stylesheets">
    <link rel="stylesheet" href="webform.css" type="text/css" />
    <style type="text/css">
        .auto-style1 {
            width: 20%;
            height: 85px;
        }
        .auto-style2 {
            width: 70%;
            height: 85px;
        }
        .auto-style3 {
            width: 20%;
            height: 72px;
        }
        .auto-style4 {
            width: 70%;
            height: 72px;
        }
    </style>
</asp:Content>


