<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="SupplierForm.aspx.cs" Inherits="TSQLWEB.SupplierForm"  ValidateRequest="true"%>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br/>
	<div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Supplier Form</h3>
        </div>
        <div class="panel-body">
          <table cellpadding="5px">
	<tr >
	<td style="width: 20%; text-align:right" > Company Name:</td>
	<td style="width: 70%"><asp:TextBox ID="txtCompanyName" cssClass="form-control" runat="server" Width="206px"/><asp:RequiredFieldValidator runat="server" ControlToValidate="txtCompanyName"
                    CssClass="text-danger" ErrorMessage="The Company name field is required." /></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Contact Name:</td>
	<td style="width: 70%"><asp:TextBox ID="txtContactName" cssClass="form-control" runat="server" Width="206px"/><asp:RequiredFieldValidator runat="server" ControlToValidate="txtContactName"
                    CssClass="text-danger" ErrorMessage="The Contact name field is required." /></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Contact Title:</td>
	<td style="width: 70%"><asp:TextBox ID="txtContactTitle" cssClass="form-control" runat="server" Width="206px"></asp:TextBox></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Address:</td>
	<td style="width: 70%"><asp:TextBox ID="txtAddress" cssClass="form-control" runat="server" Width="206px"></asp:TextBox></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">City:</td>
	<td style="width: 70%"><asp:TextBox ID="txtCity" cssClass="form-control" runat="server" Width="206px"></asp:TextBox></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Region:</td>
	<td style="width: 70%"><asp:TextBox ID="txtRegion" cssClass="form-control" runat="server" Width="206px"></asp:TextBox></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Postal Code:</td>
	<td style="width: 70%"><asp:TextBox ID="txtPostalCode" cssClass="form-control" runat="server" Width="206px"></asp:TextBox></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Country:</td>
	<td style="width: 70%"><asp:DropDownList ID="cbCountry" cssClass="form-control" runat="server" Width="206px">
        <asp:ListItem Value="-1">Choose a national</asp:ListItem>
        <asp:ListItem>Vietnamese</asp:ListItem>
        <asp:ListItem>Japan</asp:ListItem>
        <asp:ListItem>USA</asp:ListItem>
        <asp:ListItem>UK</asp:ListItem>
        <asp:ListItem>French</asp:ListItem>
        <asp:ListItem>Canada</asp:ListItem>
        <asp:ListItem>Cuba</asp:ListItem>
    </asp:DropDownList></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Phone:</td>
	<td style="width: 70%"><asp:TextBox ID="txtPhone" cssClass="form-control" runat="server" Width="206px"></asp:TextBox></td>
	</tr>
	<tr>
	<td style="width: 20%; text-align:right">Fax:</td>
	<td style="width: 70%"><asp:TextBox ID="txtFax" cssClass="form-control" runat="server" Width="206px"></asp:TextBox></td>
	</tr>
</table>

        </div>
      </div>
	


    <br />
	<div class="btn btn-default"> <asp:Button ID="btnNew"  runat="server" Text="New" OnClick="btnNew_Click" /></div>
    <div class="btn btn-success"> <asp:Button ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click" /> </div>
		
    <script>
   </script>
        <div id="alert" class="alert alert-success fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">Close &times;</a>
    <strong>Success!</strong> Add completely! 
    </div>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateSelectButton="True" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
	</asp:GridView>

    <br />
</asp:Content>
